//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telesyk.StockQuotes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telesyk.StockQuotes.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середнє аріфметичне.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router Quantity.
        /// </summary>
        internal static string Configuration_Name_RouterQuantity {
            get {
                return ResourceManager.GetString("Configuration_Name_RouterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартне відхилення.
        /// </summary>
        internal static string Divergence {
            get {
                return ResourceManager.GetString("Divergence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Втрачено пакетів.
        /// </summary>
        internal static string Losted {
            get {
                return ResourceManager.GetString("Losted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальне значення.
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медіана.
        /// </summary>
        internal static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мінімальне значення.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторів у модах.
        /// </summary>
        internal static string ModeDuplicates {
            get {
                return ResourceManager.GetString("ModeDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моди.
        /// </summary>
        internal static string Modes {
            get {
                return ResourceManager.GetString("Modes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума значень.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Унікальних значень.
        /// </summary>
        internal static string UniqueCount {
            get {
                return ResourceManager.GetString("UniqueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість значень.
        /// </summary>
        internal static string ValueCount {
            get {
                return ResourceManager.GetString("ValueCount", resourceCulture);
            }
        }
    }
}
